import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/navbar'
import React from 'react'
import LogContextProvider from './Components/Log/LogContext'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<LogContextProvider>
					<Navbar />
					{children}
				</LogContextProvider>
			</body>
		</html>
	)
}
