
export interface Api{
	SignIn : string,
	SignUp : string,
	Profile : string,
	Navbar: string,
	accessToken: string,
	googleAuth: string,
	intraAuth: string,
	googleToken: string,
	intraToken: string,
	Search : string,
	SendFriendRequest : string,
	User : string,
	Remove: string,
	getChat: string,
	sendMsg : string,
	Friends: string,
	Kick: string,
	Ban: string,
	Mute: string,
	MakeAdmin: string,
	RemoveAdmin: string,
	Groups : string,
	myGroups : string,
	JoinRoom : string,
	CreateRoom : string,
	LeaveRoom : string,
	Block : string,
	JoinProtectedRoom : string,
	addMember: string,
	UnBan : string,
	RoomChat : string,
	members: string,
}

export const APIs : Api = { 
	SignIn : "http://localhost:3001/auth/signIn",
	SignUp : "http://localhost:3001/auth/signUp",
	Profile : "http://localhost:3001/user/profile",
	User : "http://localhost:3001/user/?username=",
	Navbar: "http://localhost:3001/user/profile",
	accessToken: "http://localhost:3001/auth/token",
	googleAuth: "http://localhost:3001/auth/google",
	intraAuth: "http://localhost:3001/auth/intra",
	googleToken: "http://localhost:3001/auth/google/callback",
	intraToken: "http://localhost:3001/auth/intra/callback",
	Search : "http://localhost:3001/user/search/?username=",
	SendFriendRequest : "http://localhost:3001/request/",
	Remove: "http://localhost:3001/user/remove",
	getChat: "http://localhost:3001/message/chat/?username=",
	sendMsg : "http://localhost:3001/message/send",
	Friends: "http://localhost:3001/user/friends/?chat=",
	Ban: "http://localhost:3001/room/ban/member",
	UnBan: "http://localhost:3001/room/unban/member",
	addMember: "http://localhost:3001/room/add/member",
	Kick: "http://localhost:3001/room/remove/member",
	Mute: "http://localhost:3001/role/mute",
	MakeAdmin: "http://localhost:3001/room/add/admin",
	RemoveAdmin: "http://localhost:3001/room/remove/admin",
	Groups : "http://localhost:3001/room",
	myGroups : "http://localhost:3001/room/in",
	JoinRoom : "http://localhost:3001/room/join",
	CreateRoom : "http://localhost:3001/room/create",
	LeaveRoom : "http://localhost:3001/room/leave",
	Block : "http://localhost:3001/user/block",
	JoinProtectedRoom : "http://localhost:3001/room/join/protected",
	RoomChat : "http://localhost:3001/room/chat/?id=",
	members: "http://localhost:3001/room/members/?id=",
};